// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIXPcqdyj83_wAdVvw8HUWwciCX92VNzA',
    appId: '1:711050661583:web:5d620c9d39c21e9315f1ba',
    messagingSenderId: '711050661583',
    projectId: 'smsapp-9b81e',
    authDomain: 'smsapp-9b81e.firebaseapp.com',
    storageBucket: 'smsapp-9b81e.firebasestorage.app',
    measurementId: 'G-31PW0WTDP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWTAqJ2LtO9W_AKgxvG0k8kQqwNsS61B0',
    appId: '1:711050661583:android:710bdde35f35604015f1ba',
    messagingSenderId: '711050661583',
    projectId: 'smsapp-9b81e',
    storageBucket: 'smsapp-9b81e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfpqVbuapGrHvcLNjP77Kl1Zh4PSFirJg',
    appId: '1:711050661583:ios:8781b16a899e428a15f1ba',
    messagingSenderId: '711050661583',
    projectId: 'smsapp-9b81e',
    storageBucket: 'smsapp-9b81e.firebasestorage.app',
    iosBundleId: 'com.example.smsApp',
  );
}
